name: square_in_app_payments_example
description: Demonstrates how to use the square_in_app_payments plugin.

version: 1.1.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  uuid: ^3.0.6

dev_dependencies:
  square_in_app_payments:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
