matrix:
  include:
  - language: android
    sudo: false
    jdk: oraclejdk8
    os:
    - linux
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-29.0.2
      - android-29
      - extra-google-google_play_services
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_install:
    - cd example
    - yes | sdkmanager "platforms;android-28"
    install:
    - git clone https://github.com/flutter/flutter.git -b stable --depth 1
    - "./flutter/bin/flutter doctor"
    script:
    - "./flutter/bin/flutter -v build apk"
  - language: objective-c
    os: osx
    osx_image: xcode12
    cache:
      directories:
      - "$HOME/.pub-cache"
    before_install:
    - cd example
    - sudo gem install cocoapods
    - pod setup
    - git clone https://github.com/flutter/flutter.git -b stable --depth 1
    - "./flutter/bin/flutter doctor"
    - pod repo update
    script:
    - "./flutter/bin/flutter -v build ios --no-codesign"
notifications:
  slack:
    secure: B0ay5XBcTmRSrgQb2PY9KjfRCejJVoYLE3hh7YINx6dcCEwoj7k+Woi3nfxNGiZcCvjxL9uAh2BwFfeWS6JW52aItfCT3Y5Ma8SIxmRLOh2Hhsr3+ZmPukTfqevu4KqKrGOwrRjPbP+bjsV/zsNAMhXIvTPWa5Sb2I7S/sdrLJZUv/ihc2+NOg3y903c99p1bVN/qSAs8LPxV7NMPE07uJ9kAOs5d2nsm88YYPPAX8Dg3OFUn2qrKQnA3TWdtJmKVAw3jFoJF8Op5JhvhaCawjVqK/RKuO+KRvdPFfRqAUBuLzay2dwwewfe3Ucy/6orUbwUf5rE0AyezVV7CCGfCfE6y1gd9XHVIAJIDQUxYn2zrnpqMBwZcCUSENToFWhaq+3dtxhrzXu3gxPTKb4tnAmChEGLRl2bK8MlA+8lsYxvXrpoHivsHZbSsR9xYz75RFSWgfzLC2hChDkWBbz0tviDWDNEBsktvOPQTmnU4Jx69iCinjjNT8RdSkMrn/eh0lBaqCfUbNGyIcMlqQ+4a89O41mkx7EomM2jKjm1Y5Uxf1KinkJvydyJso1knUyVV6yMjuitN9fLCqeLX+zWvgUrAT2Iqs9BSPf7vNnVs09nQFjFE2WwA+OuVWAE4n3og7FuhA3pwiA3y9oSSm0tHR1CWVeVei10DPmqdjQ0G+0=
    on_success: change
    template:
        - "@oncall"
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
  email:
    recipients:
      - devs-apex-alerts+travis@squareup.com
    on_success: change
