name: square_in_app_payments
description: An open source Flutter plugin for calling Squareâ€™s native In-App Payments SDK to take in-app payments on iOS and Android.
version: 1.8.0
homepage: https://github.com/square/in-app-payments-flutter-plugin
documentation: https://github.com/square/in-app-payments-flutter-plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.4
  built_collection: ^5.0.0
  meta: ^1.1.6

dev_dependencies:
  build: ^2.0.0
  build_runner: ^1.12.2
  source_gen:  ^1.0.0
  built_value_generator: ^8.0.4

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: sqip.flutter
        pluginClass: SquareInAppPaymentsFlutterPlugin
      ios:
        pluginClass: SquareInAppPaymentsFlutterPlugin
