name: square_in_app_payments
description: An open source Flutter plugin for calling Squareâ€™s native In-App Payments SDK to take in-app payments on iOS and Android.
version: 1.0.0
author: Square Flutter Team <flutter-team@squareup.com>
homepage: https://github.com/square/in-app-payments-flutter-plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: "^6.1.5"

dev_dependencies:
  build:
  build_runner:
  source_gen:
  built_value_generator:

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: sqip.flutter
    pluginClass: SquareInAppPaymentsFlutterPlugin